object FrmAgendamento: TFrmAgendamento
  Left = 0
  Top = 0
  BorderStyle = bsNone
  ClientHeight = 425
  ClientWidth = 377
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 15
  object PnlFundo: TPanel
    Left = 0
    Top = 0
    Width = 377
    Height = 425
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    ExplicitLeft = 144
    ExplicitTop = 128
    ExplicitWidth = 185
    ExplicitHeight = 41
    DesignSize = (
      377
      425)
    object LblProfissionais: TLabel
      Left = 24
      Top = 16
      Width = 179
      Height = 20
      Caption = '1 - Selecione o Profissional'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 12105912
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object BtnProfissional: TSpeedButton
      Left = 24
      Top = 42
      Width = 25
      Height = 28
      Glyph.Data = {
        E6040000424DE604000000000000360000002800000014000000140000000100
        180000000000B0040000C40E0000C40E00000000000000000000FFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFCFF6BA2FF6BA2FFFBFCFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFC5DBFF005FFF005FFFC6DBFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFBFD7FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFBFD7FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7
        FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF
        005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF005FFFBF
        D7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFCFF
        C4DAFFBBD4FFBBD4FFBBD4FFBBD4FFBBD4FF8CB7FF005FFF005FFF8CB7FFBBD4
        FFBBD4FFBBD4FFBBD4FFBBD4FFC4DAFFFBFCFFFFFFFFFFFFFF6AA2FF005FFF00
        5FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF
        005FFF005FFF005FFF005FFF6BA2FFFFFFFFFFFFFF69A1FF005FFF005FFF005F
        FF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF00
        5FFF005FFF005FFF6BA2FFFFFFFFFFFFFFFBFCFFC3D9FFBBD4FFBBD4FFBBD4FF
        BBD4FFBBD4FF8CB7FF005FFF005FFF8CB7FFBBD4FFBBD4FFBBD4FFBBD4FFBBD4
        FFC3D9FFFBFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFBFD7FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7
        FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF
        005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF005FFFBF
        D7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF005FFFBFD7FFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFC5DBFF005FFF005FFFC6DBFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFBFCFF69A1FF6AA2FFFBFCFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFF}
      OnClick = BtnProfissionalClick
    end
    object BtnDataHora: TSpeedButton
      Left = 24
      Top = 114
      Width = 25
      Height = 28
      Glyph.Data = {
        E6040000424DE604000000000000360000002800000014000000140000000100
        180000000000B0040000C40E0000C40E00000000000000000000FFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFCFF6BA2FF6BA2FFFBFCFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFC5DBFF005FFF005FFFC6DBFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFBFD7FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFBFD7FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7
        FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF
        005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF005FFFBF
        D7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFCFF
        C4DAFFBBD4FFBBD4FFBBD4FFBBD4FFBBD4FF8CB7FF005FFF005FFF8CB7FFBBD4
        FFBBD4FFBBD4FFBBD4FFBBD4FFC4DAFFFBFCFFFFFFFFFFFFFF6AA2FF005FFF00
        5FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF
        005FFF005FFF005FFF005FFF6BA2FFFFFFFFFFFFFF69A1FF005FFF005FFF005F
        FF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF005FFF00
        5FFF005FFF005FFF6BA2FFFFFFFFFFFFFFFBFCFFC3D9FFBBD4FFBBD4FFBBD4FF
        BBD4FFBBD4FF8CB7FF005FFF005FFF8CB7FFBBD4FFBBD4FFBBD4FFBBD4FFBBD4
        FFC3D9FFFBFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFBFD7FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7
        FF005FFF005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF
        005FFFBFD7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF005FFFBF
        D7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFD7FF005FFF005FFFBFD7FFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFC5DBFF005FFF005FFFC6DBFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFBFCFF69A1FF6AA2FFFBFCFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFF}
    end
    object LblDiaHorario: TLabel
      Left = 24
      Top = 88
      Width = 112
      Height = 20
      Caption = '2 - Dia e Hor'#225'rio'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 12105912
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object BtnBuscaCliente: TSpeedButton
      Left = 24
      Top = 188
      Width = 25
      Height = 29
      Glyph.Data = {
        E6040000424DE604000000000000360000002800000014000000140000000100
        180000000000B0040000C40E0000C40E00000000000000000000FFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFE9F1FF4086FF649EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE9
        F1FF2C7BFF005FFF3E86FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEAF2FF2D7AFF005F
        FF2877FFE6EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEAF2FF2D7AFF005FFF2877FFE6EFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFEAF2FF2D7AFF005FFF2877FFE6EFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFF5FFA9C9FF82B1FF8FB9FFC5DBFF
        FEFEFFFFFFFF5091FF005FFF2C7BFFE9F1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFF91BAFF0E68FF1B70FF4B8DFF3B83FF0762FF337FFFD3
        E3FF96BDFF4D8FFFE9F1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFF79ABFF1068FFA9C9FFFEFEFFFFFFFFFFFFFFECF3FF5F9BFF0E68FFD3E3
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7DCFF04
        62FFC6DBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F9BFF337FFFFEFEFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D99FF5C99FFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBF2FF0762FFC5DBFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2677FFA3C5FFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3C85FF8DB7FFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1D70FFAFCDFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFF488BFF84B2FFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFF4086FF82B1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFEFEFF1B70FFA8C8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFF95BCFF1E72FFF5F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFA6C7FF0F67FFF0F6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFF9FBFF2E7CFF4D8FFFF5F9FFFFFFFFFFFFFFFFFFFFFFFFFFC4DAFF0F
        67FF93BBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFE3EDFF2E7CFF1E72FF82B1FFB0CDFFA2C5FF5B97FF0462FF7CADFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFF9FBFF95BCFF4086FF1B70FF2777FF5E9AFFC9DDFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFF}
    end
    object LblCliente: TLabel
      Left = 24
      Top = 162
      Width = 149
      Height = 20
      Caption = '3 - Selecione o Cliente'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 12105912
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object LblTelefone: TLabel
      Left = 24
      Top = 237
      Width = 57
      Height = 20
      Caption = 'Telefone'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 12105912
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object LblCelular: TLabel
      Left = 183
      Top = 237
      Width = 46
      Height = 20
      Caption = 'Celular'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 12105912
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object LblObs: TLabel
      Left = 24
      Top = 310
      Width = 106
      Height = 20
      Caption = '4 - Observa'#231#245'es'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 12105912
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
    end
    object DBLCmBProfissionais: TDBLookupComboBox
      Left = 48
      Top = 42
      Width = 305
      Height = 28
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object DBMEdtData: TSWHMaskEdit
      Left = 48
      Top = 114
      Width = 145
      Height = 28
      EditMask = '99/99/9999;0;_'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 10
      ParentFont = False
      TabOrder = 1
      Text = ''
      MudarColor = 14087422
      TipoMascara = tmData
    end
    object DBMEdtHora: TSWHMaskEdit
      Left = 199
      Top = 114
      Width = 154
      Height = 28
      EditMask = '99:99;1;_'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      MaxLength = 5
      ParentFont = False
      TabOrder = 2
      Text = '  :  '
      MudarColor = 14087422
      TipoMascara = tmData
    end
    object EdtCliente: TSWHEdit
      Left = 48
      Top = 188
      Width = 305
      Height = 28
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      ControlarDigitacao = False
      MudarColor = 14087422
    end
    object DBMEdtTelefone: TSWHMaskEdit
      Left = 24
      Top = 263
      Width = 135
      Height = 29
      EditMask = '(99)9999-9999;0;_'
      MaxLength = 13
      TabOrder = 4
      Text = ''
      MudarColor = 14087422
      TipoMascara = tmTelefone
    end
    object DBMEdtCelular: TSWHMaskEdit
      Left = 183
      Top = 263
      Width = 170
      Height = 29
      EditMask = '(99)9999-9999;0;_'
      MaxLength = 13
      TabOrder = 5
      Text = ''
      MudarColor = 14087422
      TipoMascara = tmCelular
    end
    object DBEdtObs: TSWHEdit
      Left = 24
      Top = 328
      Width = 329
      Height = 29
      TabOrder = 6
      ControlarDigitacao = False
      MudarColor = 14087422
    end
    object PnlBtns: TPanel
      Left = 70
      Top = 366
      Width = 227
      Height = 50
      Anchors = [akTop, akRight]
      BevelOuter = bvNone
      TabOrder = 7
      object PnlBotaoConfirma: TPanel
        Left = 9
        Top = 11
        Width = 110
        Height = 33
        BevelOuter = bvNone
        Color = 33023
        ParentBackground = False
        TabOrder = 0
        object BtnConfirma: TSpeedButton
          Left = 0
          Top = 0
          Width = 110
          Height = 33
          Cursor = crHandPoint
          Align = alClient
          Caption = 'Confirmar'
          Flat = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Segoe UI'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitLeft = -11
          ExplicitTop = 6
        end
      end
      object PnlBotaoCancela: TPanel
        Left = 113
        Top = 11
        Width = 106
        Height = 33
        BevelOuter = bvNone
        Color = 15921906
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Segoe UI'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 1
        object BtnCancela: TSpeedButton
          Left = 0
          Top = 0
          Width = 106
          Height = 33
          Cursor = crHandPoint
          Align = alClient
          Caption = 'Cancelar'
          Flat = True
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clGray
          Font.Height = -13
          Font.Name = 'Segoe UI'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = BtnCancelaClick
          ExplicitWidth = 105
          ExplicitHeight = 25
        end
      end
    end
  end
end
